from django.urls import path
from django.views.i18n import set_language
from . import views

urlpatterns = [
    path('', views.home),
    path(r'^set-language/$', set_language, name='set_language'),
    path('forbidden_request', views.forbidden_request),
    path('my_view', views.my_view),
    path('switch_language/', views.switch_language, name='switch_language'),
    path('logout', views.logout_view),
    path('create_information_form', views.create_information_form),
    path('create_employee', views.create_employee),
    path('all_employee', views.list_all_employee),
    path('list_all_attachments', views.list_all_attachments),
    path('employee/<int:pk>/', views.single_employee),
    path('update_employee/<int:pk>/', views.update_employee),
    path('delete_employee/<int:pk>/', views.delete_employee),
    path('routine/<int:pk>/', views.single_routine),
    path('all_routine', views.list_all_routines),
    path('update_routine/<int:pk>/', views.update_routine),
    path('delete_routine/<int:pk>/', views.delete_routine),
    path('create_routine', views.create_routine),
    path('create_vehicle_failures', views.create_vehicle_failures),
    path('create_company_attendance', views.create_company_attendance),
    path('create_company_cases', views.create_company_cases),
    path('create_company', views.create_company),
    path('all_vehicle_failures', views.list_all_vehicle_failures),
    path('update_vehicle_failures/<int:pk>/', views.update_vehicle_failures),
    path('vehicle_failures/<int:pk>/', views.single_vehicle_failures),
    path('all_company_attendance', views.list_all_company_attendance),
    path('all_company_cases', views.list_all_company_cases),
    path('company_attendance/<int:pk>/', views.single_company_attendance),
    path('company_cases/<int:pk>/', views.single_company_cases),
    path('update_company_cases/<int:pk>/', views.update_company_cases),
    path('update_company_attendance/<int:pk>/', views.update_company_attendance),
    path('delete_company_attendance/<int:pk>/', views.delete_company_attendance),
    path('delete_company_cases/<int:pk>/', views.delete_company_cases),
    path('delete_vehicle_failures/<int:pk>/', views.delete_vehicle_failures),
    path('all_company', views.list_all_company),
    path('cases_log', views.cases_log),
    path('trafic_log', views.trafic_log),
    path('person_id', views.person_id),
    path('company/<int:pk>/', views.single_company),
    path('update_company/<int:pk>/', views.update_company),
    path('delete_company/<int:pk>/', views.delete_company),
    path('create_vehicle', views.create_vehicle),
    path('all_vehicle', views.list_all_vehicle),
    path('vehicle/<int:pk>/', views.single_vehicle),
    path('update_vehicle/<int:pk>/', views.update_vehicle),
    path('delete_vehicle/<int:pk>/', views.delete_vehicle),
    path('create_vehicle_type', views.create_vehicle_type),
    path('all_vehicle_type', views.list_all_vehicle_type),
    path('update_vehicle_type/<int:pk>/', views.update_vehicle_type),
    path('delete_vehicle_type/<int:pk>/', views.delete_vehicle_type),
    path('vehicle_type/<int:pk>/', views.single_vehicle_type),
    path('create_action', views.create_action),
    path('create_shift', views.create_shift),
    path('all_action', views.list_all_action),
    path('all_shift', views.list_all_shift),
    path('shift/<int:pk>/', views.single_shift),
    path('actions/<int:pk>/', views.single_action, name='single_action'),
    path('delete_action/<int:pk>/', views.delete_action),
    path('delete_request/<int:pk>/', views.delete_request),
    path('update_action/<int:pk>/', views.update_action),
    path('update_shift/<int:pk>/', views.update_shift),
    path('delete_action/<int:pk>/', views.delete_action),
    path('delete_shift/<int:pk>/', views.delete_shift),
    path('create_client', views.create_client),
    path('create_worklocation', views.create_worklocation),
    path('client/<int:pk>/', views.single_client),
    path('update_client/<int:pk>/', views.update_client),
    path('delete_client/<int:pk>/', views.delete_client),
    path('all_clients', views.list_all_clients),
    path('assign_employee_routine/', views.assign_employee_routine),
    path('assign_duty/', views.assign_duty),
    path('employee_duty', views.employee_duty),
    path('employee_routine', views.employee_routine),
    path('user_permission', views.user_permission),
    path('user_management', views.user_management),
    path('role_assign', views.role_assign),
    path('update_permissions', views.update_permissions),
    path('create_user', views.create_user),
    path('user/<int:pk>/', views.single_user),
    path('delete_user/<int:pk>/', views.delete_user),
    path('update_user/<int:pk>/', views.update_user),
    path('request/<int:pk>/', views.single_request),
    path('update_request/<int:pk>/', views.update_request_form),
    path('create_note', views.create_note),
    path('create_request_method/', views.create_request_method),
    path('create_request_reason/', views.create_request_reason),
    path('all_users', views.list_all_users),
    path('request_form', views.request_form),
    path('client_request_forms', views.client_request_forms),
    path('list_employee_request_form', views.list_employee_request_form),
    path('list_client_request_form', views.list_client_request_form),
    # path('attachment_form', views.attachment_form),
    path('attendance_report', views.attendance_report),
    path('request_report', views.request_report),
    path('client_report', views.client_report),
    path('employee_report/', views.employee_report),
    path('attendence', views.attendence),
    path('single_attendence', views.single_attendence),
    path('request_method_api', views.request_method_api),
    path('client_job_role_api', views.client_job_role_api),
    path('request_reason_api', views.request_reason_api),
    path('request_note_api', views.request_note_api),
    path('client_form_api', views.client_form_api),
    path('vehicle_form_api', views.vehicle_form_api),
    path('vehicle_type_api', views.vehicle_type_api),
    path('group_permissions_api', views.group_permissions_api),
    path('vehicle_type_form_api', views.vehicle_type_form_api),
    path('cases_action_api', views.cases_action_api),
    path('cases_descrption_api', views.cases_descrption_api),
    path('vehicle_failures_api', views.vehicle_failures_api),
    path('vehicle_failures_api/<int:pk>/', views.update_vehicle_failures_api),
    path('company_attendance_api', views.company_attendance_api),
    path('company_attendance_api/<int:pk>/', views.update_company_attendance_api),
    path('company_cases_api', views.company_cases_api),
    path('company_cases_api/<int:pk>/', views.update_company_cases_api),
    path('company_guard_api', views.company_guard_api),
    path('employee_form_api', views.employee_form_api),
    path('today_attendence_api', views.today_attendence_api),
    path('month_attendence_api', views.month_attendence_api),
    path('callname_api', views.callname_api),
    path('shift_form_api', views.shift_form_api),
    path('month_attendance', views.month_attendance),
    path('company_form_api', views.company_form_api),
    path('user_form_api', views.user_form_api),
    path('actions_api', views.actions_api),
    path('request_form_api', views.request_form_api),
    path('routine_form_api', views.routine_form_api),
    path('employee_request_form_api', views.employee_request_form_api),
    path('worklocation_form_api', views.worklocation_form_api),
    path('single_employee_routine_api', views.single_employee_routine_api),
    path('client_request_form_api', views.client_request_form_api),
    path('request_form/<int:pk>/', views.request_form_update),
    path('information_form_api', views.information_form_api),
    path('information_form_api_delete/<int:pk>/', views.information_form_api_delete),
    path('dashboard', views.dashboard),
    # path('user/', views.user_list),
    # path('user/<int:pk>/', views.user_detail),
    # path('department/', views.department_list),
    # path('department/<int:pk>/', views.department_detail),
    # path('employee/', views.employee_list),
    # path('employee/<int:pk>/', views.employee_detail),
    # path('duty/', views.duty_list),
    # path('duty/<int:pk>/', views.duty_detail),
    # path('client/', views.client_list),
    # path('client/<int:pk>/', views.client_detail),
    # path('note/', views.note_list),
    # path('note/<int:pk>/', views.note_detail),
    # path('request/', views.request_list),
    # path('request/<int:pk>/', views.request_detail),
    # path('requestnote/', views.requestnote_list),
    # path('requestnote/<int:pk>/', views.requestnote_detail),
    # path('worklocation/', views.worklocation_list),
    # path('worklocation/<int:pk>/', views.worklocation_detail),
    # path('attachment/', views.attachment_list),
    # path('attachment/<int:pk>/', views.attachment_detail),
    # path('requestattachment/', views.requestattachment_list),
    # path('requestattachment/<int:pk>/', views.requestattachment_detail),
    # path('attendencelog/', views.attendencelog_list),
    # path('attendencelog/<int:pk>/', views.attendencelog_detail),
    # path('notification/', views.notification_list),
    # path('notification/<int:pk>/', views.notification_detail),
]